import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { ProviderTheme } from "./provider";
import NavMenu from "@/components/menus/nav";
import Header from "@/components/menus/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dark">
      <body>
        <ProviderTheme>
          <NavMenu />
          <Header />
          <div className="content">{children}</div>
        </ProviderTheme>
      </body>
    </html>
  );
}
